#=======================================================================
# Orinal author : Gabor Grothendieck
# Original code : R-help: Sep 23, 2013 at 2:55 PM
# Topic         : Re: Vector of char generated by Sys.getenv function
#               :     is not available when the package is loaded
# Adapted by    : José Cláudio Faria
# Objective     : To supply the current necessity of the Tinn-R project
# Date          : 2013/09/24 - 17:21:07
#=======================================================================
.onLoad <- function(libname, 
                    pkgname)
{
  .trPaths <<- file.path(Sys.getenv('TEMP'),
                         'Tinn-R',
                         c('',
                           'search.txt',
                           'objects.txt',
                           'file.r',
                           'selection.r',
                           'block.r',
                           'lines.r',
                           'reformat-input.r',
                           'reformat-output.r'),
                         fsep='\\')
}
